/*
 * Competency Service OpenAPI (JSON) Definition
 *
 * The Competency Service enables the exchange of data between a Competency Records Service Provider and the consumers of the associated data. This service has been described using the IMS Model Driven Modelling approach: this being the Platform Specific Model (PSM) of the service.
 *
 * OpenAPI spec version: 1.0
 * Contact: lmattson@imsglobal.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Newtonsoft.Json;
using System.Web.Http;
using com.eLumen.Standard.Models;
using Swashbuckle.Swagger.Annotations;

namespace com.eLumen.Standard.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class RubricApiController : ApiController
    { 
        /// <summary>
        /// ...tbd...
        /// </summary>
        /// <remarks>...not supplied...</remarks>
        /// <param name="limit">To define the download segmentation value i.e. the maximum number of records to be contained in the response.</param>
        /// <param name="offset">The number of the first record to be supplied in the segmented response message.</param>
        /// <param name="sort">Identifies the sort criteria to be used for the records in the response message. Use with the orderBy parameter</param>
        /// <param name="orderBy">The form of ordering for response to the sorted request i.e. ascending (asc) or descending (desc).</param>
        /// <param name="filter">The filtering rules to be applied when identifying the records to be supplied in the response message.</param>
        /// <param name="fields">To identify the range of fields that should be supplied in the response message.</param>
        /// <response code="200">...tbd...</response>
        /// <response code="0">StatusInfo Error Report</response>
        [HttpGet]
        [Route("rubric/criteria")]
        [SwaggerOperation("GetAllRubricCriteria")]
        [SwaggerResponse(200, type: typeof(RubricCriteriaSetType))]
        public virtual RubricCriteriaSetType GetAllRubricCriteria(int? limit, int? offset, string sort, string orderBy, string filter, List<string> fields)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<RubricCriteriaSetType>(exampleJson)
            : default(RubricCriteriaSetType);
            return default(RubricCriteriaSetType);
        }


        /// <summary>
        /// ...tbd...
        /// </summary>
        /// <remarks>...not supplied...</remarks>
        /// <param name="limit">To define the download segmentation value i.e. the maximum number of records to be contained in the response.</param>
        /// <param name="offset">The number of the first record to be supplied in the segmented response message.</param>
        /// <param name="sort">Identifies the sort criteria to be used for the records in the response message. Use with the orderBy parameter</param>
        /// <param name="orderBy">The form of ordering for response to the sorted request i.e. ascending (asc) or descending (desc).</param>
        /// <param name="filter">The filtering rules to be applied when identifying the records to be supplied in the response message.</param>
        /// <param name="fields">To identify the range of fields that should be supplied in the response message.</param>
        /// <response code="200">...tbd...</response>
        /// <response code="0">StatusInfo Error Report</response>
        [HttpGet]
        [Route("rubric/criterionLevel")]
        [SwaggerOperation("GetAllRubricCriterionLevels")]
        [SwaggerResponse(200, type: typeof(RubricCriterionLevelSetType))]
        public virtual RubricCriterionLevelSetType GetAllRubricCriterionLevels(int? limit, int? offset, string sort, string orderBy, string filter, List<string> fields)
        {
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<RubricCriterionLevelSetType>(exampleJson)
            : default(RubricCriterionLevelSetType);
            return default(RubricCriterionLevelSetType);
        }


        /// <summary>
        /// ...tbd...
        /// </summary>
        /// <remarks>...not supplied...</remarks>
        /// <param name="limit">To define the download segmentation value i.e. the maximum number of records to be contained in the response.</param>
        /// <param name="offset">The number of the first record to be supplied in the segmented response message.</param>
        /// <param name="sort">Identifies the sort criteria to be used for the records in the response message. Use with the orderBy parameter</param>
        /// <param name="orderBy">The form of ordering for response to the sorted request i.e. ascending (asc) or descending (desc).</param>
        /// <param name="filter">The filtering rules to be applied when identifying the records to be supplied in the response message.</param>
        /// <param name="fields">To identify the range of fields that should be supplied in the response message.</param>
        /// <response code="200">...tbd...</response>
        /// <response code="0">StatusInfo Error Report</response>
        [HttpGet]
        [Route("rubric")]
        [SwaggerOperation("GetAllRubrics")]
        [SwaggerResponse(200, type: typeof(RubricSetType))]
        public virtual RubricSetType GetAllRubrics(int? limit, int? offset, string sort, string orderBy, string filter, List<string> fields)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<RubricSetType>(exampleJson)
            : default(RubricSetType);
            return default(RubricSetType);
        }

        /// <summary>
        /// ...tbd...
        /// </summary>
        /// <remarks>...not supplied...</remarks>
        /// <param name="sourcedId">...tbd...</param>
        /// <param name="limit">To define the download segmentation value i.e. the maximum number of records to be contained in the response.</param>
        /// <param name="offset">The number of the first record to be supplied in the segmented response message.</param>
        /// <param name="sort">Identifies the sort criteria to be used for the records in the response message. Use with the orderBy parameter</param>
        /// <param name="orderBy">The form of ordering for response to the sorted request i.e. ascending (asc) or descending (desc).</param>
        /// <param name="filter">The filtering rules to be applied when identifying the records to be supplied in the response message.</param>
        /// <param name="fields">To identify the range of fields that should be supplied in the response message.</param>
        /// <response code="200">...tbd...</response>
        /// <response code="0">StatusInfo Error Report</response>
        [HttpGet]
        [Route("rubric/{sourcedId}")]
        [SwaggerOperation("GetRubric")]
        [SwaggerResponse(200, type: typeof(RubricType))]
        public virtual RubricType GetRubric(string sourcedId, int? limit, int? offset, string sort, string orderBy, string filter, List<string> fields)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<RubricType>(exampleJson)
            : default(RubricType);
            return default(RubricType);
        }


        /// <summary>
        /// ...tbd...
        /// </summary>
        /// <remarks>...not supplied...</remarks>
        /// <param name="sourcedId">...tbd...</param>
        /// <param name="limit">To define the download segmentation value i.e. the maximum number of records to be contained in the response.</param>
        /// <param name="offset">The number of the first record to be supplied in the segmented response message.</param>
        /// <param name="sort">Identifies the sort criteria to be used for the records in the response message. Use with the orderBy parameter</param>
        /// <param name="orderBy">The form of ordering for response to the sorted request i.e. ascending (asc) or descending (desc).</param>
        /// <param name="filter">The filtering rules to be applied when identifying the records to be supplied in the response message.</param>
        /// <param name="fields">To identify the range of fields that should be supplied in the response message.</param>
        /// <response code="200">...tbd...</response>
        /// <response code="0">StatusInfo Error Report</response>
        [HttpGet]
        [Route("rubric/criteria/{sourcedId}")]
        [SwaggerOperation("GetRubricCriterion")]
        [SwaggerResponse(200, type: typeof(RubricCriterionType))]
        public virtual RubricCriterionType GetRubricCriterion(string sourcedId, int? limit, int? offset, string sort, string orderBy, string filter, List<string> fields)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<RubricCriterionType>(exampleJson)
            : default(RubricCriterionType);
            return default(RubricCriterionType);
        }


        /// <summary>
        /// ...tbd...
        /// </summary>
        /// <remarks>...not supplied...</remarks>
        /// <param name="sourcedId">...tbd...</param>
        /// <param name="limit">To define the download segmentation value i.e. the maximum number of records to be contained in the response.</param>
        /// <param name="offset">The number of the first record to be supplied in the segmented response message.</param>
        /// <param name="sort">Identifies the sort criteria to be used for the records in the response message. Use with the orderBy parameter</param>
        /// <param name="orderBy">The form of ordering for response to the sorted request i.e. ascending (asc) or descending (desc).</param>
        /// <param name="filter">The filtering rules to be applied when identifying the records to be supplied in the response message.</param>
        /// <param name="fields">To identify the range of fields that should be supplied in the response message.</param>
        /// <response code="200">...tbd...</response>
        /// <response code="0">StatusInfo Error Report</response>
        [HttpGet]
        [Route("rubric/criterionLevel/{sourcedId}")]
        [SwaggerOperation("GetRubricCriterionLevel")]
        [SwaggerResponse(200, type: typeof(RubricCriterionLevelType))]
        public virtual RubricCriterionLevelType GetRubricCriterionLevel(string sourcedId, int? limit, int? offset, string sort, string orderBy, string filter, List<string> fields)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<RubricCriterionLevelType>(exampleJson)
            : default(RubricCriterionLevelType);
            return default(RubricCriterionLevelType);
        }
    }
}
