//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.eLumen.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class asmt_scale
    {
        public asmt_scale()
        {
            this.asmt_score_level = new HashSet<asmt_score_level>();
        }
    
        public int asmt_scale_id { get; set; }
        public string name { get; set; }
        public int cardinality { get; set; }
        public string scale_type { get; set; }
        public Nullable<int> top_number_scale { get; set; }
        public string rounding_method { get; set; }
        public System.DateTime lst_mod_dt { get; set; }
        public int lst_mod_user_id { get; set; }
        public int client_id { get; set; }
        public string use_not_applicable { get; set; }
        public sbyte enabled { get; set; }
        public string zero_based_scores { get; set; }
        public bool is_default { get; set; }
    
        public virtual ICollection<asmt_score_level> asmt_score_level { get; set; }
    }
}
