//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.eLumen.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class asmt_rubric_type
    {
        public int asmt_rubric_type_id { get; set; }
        public string name { get; set; }
        public string ds { get; set; }
        public bool multiple_slo { get; set; }
        public bool direct_slo_score { get; set; }
        public System.DateTime lst_mod_dt { get; set; }
        public int lst_mod_user_id { get; set; }
        public int client_id { get; set; }
    }
}
