//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.eLumen.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class asmt_mastery_level
    {
        public asmt_mastery_level()
        {
            this.asmt_score_level = new HashSet<asmt_score_level>();
        }
    
        public int asmt_mastery_level_id { get; set; }
        public string name { get; set; }
        public string ds { get; set; }
        public Nullable<int> display_seq { get; set; }
        public System.DateTime lst_mod_dt { get; set; }
        public int client_id { get; set; }
        public Nullable<int> lst_mod_user_id { get; set; }
        public string not_applicable { get; set; }
        public Nullable<int> C_src_scale_lvl_id { get; set; }
    
        public virtual ICollection<asmt_score_level> asmt_score_level { get; set; }
    }
}
