//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.eLumen.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class asmt
    {
        public asmt()
        {
            this.asmt1 = new HashSet<asmt>();
            this.asmt11 = new HashSet<asmt>();
            this.asmt12 = new HashSet<asmt>();
            this.sloes = new HashSet<slo>();
        }
    
        public int asmt_id { get; set; }
        public Nullable<int> asmt_atid { get; set; }
        public Nullable<int> previous_asmt_id { get; set; }
        public Nullable<sbyte> current_flag { get; set; }
        public sbyte is_latest { get; set; }
        public System.DateTime lst_mod_dt { get; set; }
        public int lst_mod_user_id { get; set; }
        public int client_id { get; set; }
        public bool is_shared { get; set; }
        public string new_activity_ds { get; set; }
        public Nullable<int> new_activity_type_id { get; set; }
        public Nullable<bool> for_library { get; set; }
        public Nullable<bool> C_makeMeCollective { get; set; }
        public Nullable<bool> C_was_unused_sa { get; set; }
        public Nullable<int> C_src_sa_id { get; set; }
        public Nullable<int> C_src_pa_id { get; set; }
        public string new_activity_name { get; set; }
        public Nullable<int> activity_specified { get; set; }
        public string score_type { get; set; }
        public string scard_view { get; set; }
        public string rub_view { get; set; }
        public string name { get; set; }
        public string activity_specified_ds { get; set; }
        public Nullable<int> dist_source_asmt_id { get; set; }
        public string status { get; set; }
        public sbyte is_deleted { get; set; }
        public string enable_activity { get; set; }
        public Nullable<int> default_distribution_id { get; set; }
        public Nullable<int> current_version { get; set; }
        public string student_self_asmt_enabled { get; set; }
        public string is_dla { get; set; }
        public Nullable<int> use_activity_benchmark { get; set; }
        public Nullable<decimal> passing_score { get; set; }
        public bool cascade_status { get; set; }
        public int disabled_by_scoring_setting { get; set; }
        public string sloList { get; set; }
        public Nullable<int> sloCount { get; set; }
        public bool is_portfolio { get; set; }
        public Nullable<int> portfolio_template_id { get; set; }
        public string is_multi_rater { get; set; }
        public string is_allow_annotations { get; set; }
    
        public virtual ICollection<asmt> asmt1 { get; set; }
        public virtual asmt asmt2 { get; set; }
        public virtual ICollection<asmt> asmt11 { get; set; }
        public virtual asmt asmt3 { get; set; }
        public virtual ICollection<asmt> asmt12 { get; set; }
        public virtual asmt asmt4 { get; set; }
        public virtual ICollection<slo> sloes { get; set; }
    }
}
