//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.eLumen.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class credential
    {
        public credential()
        {
            this.credential1 = new HashSet<credential>();
            this.credential11 = new HashSet<credential>();
            this.slo_class = new HashSet<slo_class>();
        }
    
        public int credential_id { get; set; }
        public Nullable<int> credential_atid { get; set; }
        public Nullable<int> previous_credential_id { get; set; }
        public Nullable<bool> current_flag { get; set; }
        public sbyte is_latest { get; set; }
        public Nullable<int> starting_term_id { get; set; }
        public Nullable<int> credential_type_id { get; set; }
        public string name { get; set; }
        public string ds { get; set; }
        public int lst_mod_user_id { get; set; }
        public System.DateTime lst_mod_dt { get; set; }
        public int client_id { get; set; }
        public Nullable<int> active_flag { get; set; }
        public Nullable<int> org_entity_id { get; set; }
        public Nullable<int> transferability_id { get; set; }
        public string program_mode { get; set; }
        public string C_external_credential_id { get; set; }
        public string top_code { get; set; }
    
        public virtual ICollection<credential> credential1 { get; set; }
        public virtual credential credential2 { get; set; }
        public virtual ICollection<credential> credential11 { get; set; }
        public virtual credential credential3 { get; set; }
        public virtual ICollection<slo_class> slo_class { get; set; }
    }
}
