//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.eLumen.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class elumenEntities : DbContext
    {
        public elumenEntities()
            : base("name=elumenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<asmt> asmts { get; set; }
        public DbSet<asmt_mastery_level> asmt_mastery_level { get; set; }
        public DbSet<asmt_perf_description> asmt_perf_description { get; set; }
        public DbSet<asmt_perf_ds_default> asmt_perf_ds_default { get; set; }
        public DbSet<asmt_rubric_type> asmt_rubric_type { get; set; }
        public DbSet<asmt_scale> asmt_scale { get; set; }
        public DbSet<asmt_score_level> asmt_score_level { get; set; }
        public DbSet<asmt_slo_criteria> asmt_slo_criteria { get; set; }
        public DbSet<new_course> new_course { get; set; }
        public DbSet<slo> sloes { get; set; }
        public DbSet<slo_asmt_scale> slo_asmt_scale { get; set; }
        public DbSet<slo_category> slo_category { get; set; }
        public DbSet<slo_class> slo_class { get; set; }
        public DbSet<credential> credentials { get; set; }
    }
}
