//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.eLumen.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class new_course
    {
        public new_course()
        {
            this.new_course1 = new HashSet<new_course>();
            this.new_course11 = new HashSet<new_course>();
            this.sloes = new HashSet<slo>();
        }
    
        public int new_course_id { get; set; }
        public Nullable<int> new_course_atid { get; set; }
        public Nullable<int> previous_new_course_id { get; set; }
        public Nullable<sbyte> current_flag { get; set; }
        public sbyte is_latest { get; set; }
        public Nullable<int> starting_term_id { get; set; }
        public string name { get; set; }
        public string short_title { get; set; }
        public string ds { get; set; }
        public Nullable<int> recommended_enrollment { get; set; }
        public int client_id { get; set; }
        public int lst_mod_user_id { get; set; }
        public System.DateTime lst_mod_dt { get; set; }
        public int org_entity_id { get; set; }
        public int status_id { get; set; }
        public string inactive_flag { get; set; }
        public Nullable<int> new_course_type_id { get; set; }
        public string num_credits { get; set; }
        public Nullable<sbyte> eligible_for_audit { get; set; }
        public Nullable<int> course_duration_minimum { get; set; }
        public Nullable<int> course_duration_maximum { get; set; }
        public Nullable<int> retake_policy { get; set; }
        public string retake_policy_description { get; set; }
        public Nullable<int> transferability_id { get; set; }
        public string comparable_course { get; set; }
        public Nullable<sbyte> is_credit_by_exam { get; set; }
        public Nullable<int> master_discipline_preferred_id { get; set; }
        public Nullable<int> alternate_master_discipline_id { get; set; }
        public Nullable<int> additional_non_master_discipline_id { get; set; }
        public Nullable<int> lecture_hours { get; set; }
        public Nullable<int> distance_ed_hours { get; set; }
        public Nullable<int> homework_hours { get; set; }
        public Nullable<int> work_based_learning_hours { get; set; }
        public Nullable<int> clinical_hours { get; set; }
        public Nullable<int> field_trip_hours { get; set; }
        public Nullable<int> lab_hours { get; set; }
        public Nullable<int> other_hours { get; set; }
        public Nullable<int> max_other_hours { get; set; }
        public string certifications { get; set; }
        public Nullable<int> additional_master_discipline_id { get; set; }
        public string notes_for_students { get; set; }
        public string course_outline_free_text { get; set; }
        public Nullable<sbyte> me_homework { get; set; }
        public Nullable<sbyte> me_tests { get; set; }
        public Nullable<sbyte> me_final_exam { get; set; }
        public Nullable<sbyte> me_project { get; set; }
        public Nullable<sbyte> me_participation { get; set; }
        public string me_description { get; set; }
        public string equipment_needed { get; set; }
        public string methods_of_instruction { get; set; }
        public string out_of_class_assignments { get; set; }
        public string object_type { get; set; }
        public string code { get; set; }
        public string course_subject { get; set; }
        public string course_number { get; set; }
        public string course_suffix { get; set; }
        public string course_control_number { get; set; }
        public Nullable<int> old_course_id { get; set; }
        public Nullable<int> old_context_id { get; set; }
        public Nullable<int> C_src_course_id { get; set; }
        public Nullable<int> C_src_ssa_id { get; set; }
        public Nullable<int> has_coordinator { get; set; }
        public Nullable<int> coordinator_manage_courses { get; set; }
        public Nullable<int> coordinator_manage_evaluators { get; set; }
        public Nullable<int> coordinator_manage_collective { get; set; }
        public string top_code { get; set; }
        public string top_name { get; set; }
        public string cip_code { get; set; }
        public string cip_name { get; set; }
        public Nullable<int> sam_code_id { get; set; }
        public Nullable<int> was_shared { get; set; }
        public Nullable<int> max_lecture_hours { get; set; }
        public Nullable<int> max_lab_hours { get; set; }
        public Nullable<int> ttl_lecture_hours { get; set; }
        public Nullable<int> ttl_max_lecture_hours { get; set; }
        public Nullable<int> ttl_lab_hours { get; set; }
        public Nullable<int> ttl_max_lab_hours { get; set; }
        public string requested_start_semester { get; set; }
        public string requested_start_year { get; set; }
        public string uc_approval_semester { get; set; }
        public string uc_approval_year { get; set; }
        public string csu_approval_semester { get; set; }
        public string csu_approval_year { get; set; }
        public string csu_ge_approval_semester { get; set; }
        public string csu_ge_approval_year { get; set; }
        public string igetc_semester { get; set; }
        public string igetc_year { get; set; }
        public string is_comments { get; set; }
        public string history { get; set; }
        public string impact_cert_text { get; set; }
        public string impact_class_text { get; set; }
        public Nullable<bool> advisory_committee_recommended { get; set; }
        public Nullable<System.DateTime> advisory_recommended_date { get; set; }
        public Nullable<bool> field_trip_requirement { get; set; }
        public string recommended_enrollment_justification { get; set; }
        public string retake_policy_justification { get; set; }
        public string starting_term_justification { get; set; }
        public Nullable<int> unit_hrs { get; set; }
        public Nullable<int> max_unit_hrs { get; set; }
        public Nullable<int> credit_hrs { get; set; }
        public Nullable<int> max_credit_hrs { get; set; }
        public string student_population { get; set; }
        public Nullable<int> course_workflow_json_history_id { get; set; }
        public string course_delivery_type { get; set; }
        public Nullable<int> max_num_credits { get; set; }
        public Nullable<int> min_num_credits { get; set; }
        public string cb12 { get; set; }
        public string can_code { get; set; }
        public string can_seq_code { get; set; }
        public string cb16 { get; set; }
        public string cb17 { get; set; }
        public string cb18 { get; set; }
        public string crosswalk_course_dept { get; set; }
        public string crosswalk_course_number { get; set; }
        public Nullable<int> time_for_review_quantity { get; set; }
        public string time_for_review_measure { get; set; }
        public Nullable<System.DateTime> approved_date { get; set; }
        public string course_uuid { get; set; }
    
        public virtual ICollection<new_course> new_course1 { get; set; }
        public virtual new_course new_course2 { get; set; }
        public virtual ICollection<new_course> new_course11 { get; set; }
        public virtual new_course new_course3 { get; set; }
        public virtual ICollection<slo> sloes { get; set; }
    }
}
