//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.eLumen.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class slo
    {
        public slo()
        {
            this.asmt_perf_ds_default = new HashSet<asmt_perf_ds_default>();
            this.asmt_slo_criteria = new HashSet<asmt_slo_criteria>();
            this.slo1 = new HashSet<slo>();
            this.slo11 = new HashSet<slo>();
            this.asmts = new HashSet<asmt>();
        }
    
        public int slo_id { get; set; }
        public Nullable<int> slo_atid { get; set; }
        public Nullable<int> previous_slo_id { get; set; }
        public Nullable<sbyte> current_flag { get; set; }
        public sbyte is_latest { get; set; }
        public string name { get; set; }
        public Nullable<decimal> performance { get; set; }
        public Nullable<int> starting_term_id { get; set; }
        public int lst_mod_user_id { get; set; }
        public System.DateTime lst_mod_dt { get; set; }
        public int client_id { get; set; }
        public Nullable<int> owner_org_entity_id { get; set; }
        public Nullable<int> slo_type_id { get; set; }
        public int slo_outcome_level_id { get; set; }
        public Nullable<int> slo_category_id { get; set; }
        public Nullable<int> new_course_id { get; set; }
        public Nullable<int> seq { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> C_src_aa_id { get; set; }
        public Nullable<int> C_src_ag_id { get; set; }
        public Nullable<int> C_src_bmg_id { get; set; }
        public Nullable<int> C_src_bm_id { get; set; }
        public Nullable<int> C_src_bmc_id { get; set; }
        public Nullable<int> C_src_ca_id { get; set; }
        public Nullable<int> C_src_cip_id { get; set; }
    
        public virtual ICollection<asmt_perf_ds_default> asmt_perf_ds_default { get; set; }
        public virtual ICollection<asmt_slo_criteria> asmt_slo_criteria { get; set; }
        public virtual new_course new_course { get; set; }
        public virtual ICollection<slo> slo1 { get; set; }
        public virtual slo slo2 { get; set; }
        public virtual ICollection<slo> slo11 { get; set; }
        public virtual slo slo3 { get; set; }
        public virtual slo_category slo_category { get; set; }
        public virtual ICollection<asmt> asmts { get; set; }
    }
}
