//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.eLumen.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class slo_asmt_scale
    {
        public int slo_asmt_scale_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string code { get; set; }
        public int client_id { get; set; }
        public Nullable<int> lst_mod_user_id { get; set; }
        public System.DateTime lst_mod_dt { get; set; }
        public Nullable<int> display_seq { get; set; }
    }
}
