//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.eLumen.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class slo_class
    {
        public slo_class()
        {
            this.slo_category = new HashSet<slo_category>();
        }
    
        public int slo_class_id { get; set; }
        public string name { get; set; }
        public string ds { get; set; }
        public string mission_stm { get; set; }
        public int org_entity_id { get; set; }
        public int slo_outcome_level_id { get; set; }
        public System.DateTime lst_mod_dt { get; set; }
        public int lst_mod_user_id { get; set; }
        public int client_id { get; set; }
        public Nullable<int> seq { get; set; }
        public Nullable<sbyte> bool_cert_and_deg { get; set; }
        public Nullable<sbyte> bool_standards_body { get; set; }
        public string standards_body_ds { get; set; }
        public sbyte use_category { get; set; }
        public Nullable<sbyte> is_third_party_standard_set { get; set; }
        public Nullable<bool> is_gen_ed { get; set; }
        public Nullable<int> owner_credential { get; set; }
    
        public virtual ICollection<slo_category> slo_category { get; set; }
        public virtual credential credential { get; set; }
    }
}
